language: python
python:
  - 2.7


before_install:
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
  - "pip install six nose nose-cov --use-mirrors"
  - "python setup.py install"
    # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

script:
  - nosetests -v --with-cover --cover-package=sos --cover-html --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_sos_f74a5ed5b9_4
  - python -m properform Push 47.88.50.110:15554 asdf_sos_f74a5ed5b9_4 ./profile_sos_f74a5ed5b9_4
 #2017-08-12 10:35:56 modified at 0 #2017-08-12 10:36:01 modified at 1 #2017-08-12 10:36:05 modified at 2 #2017-08-12 10:36:10 modified at 3 #2017-08-12 10:36:14 modified at 4