language: python
python:
  - 2.7
before_install:
 # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - "pip install six nose nose-cov pep8 --use-mirrors"
  - "python setup.py install"
    # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


script:
  - "pep8 sos"
  - nosetests -v --with-cover --cover-package=sos --cover-html --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_sos_29f388bf5b_3
  - python -m properform Push 47.88.50.110:15554 asdf_sos_29f388bf5b_3 ./profile_sos_29f388bf5b_3

 #2017-08-12 10:11:55 modified at 0 #2017-08-12 10:11:59 modified at 1 #2017-08-12 10:12:04 modified at 2 #2017-08-12 10:12:08 modified at 3